import XCTest
@testable import ReadDown

final class MarkdownRendererTests: XCTestCase {

    // MARK: - Headings

    func testHeadings() {
        XCTAssertEqual(MarkdownRenderer.render("# Hello").html, "<h1 id=\"hello\">Hello</h1>")
        XCTAssertEqual(MarkdownRenderer.render("## Hello").html, "<h2 id=\"hello\">Hello</h2>")
        XCTAssertEqual(MarkdownRenderer.render("### Hello").html, "<h3 id=\"hello\">Hello</h3>")
        XCTAssertEqual(MarkdownRenderer.render("###### Hello").html, "<h6 id=\"hello\">Hello</h6>")
    }

    func testHeadingWithInlineFormatting() {
        let result = MarkdownRenderer.render("# Hello **world**").html
        XCTAssertTrue(result.contains("<strong>world</strong>"))
    }

    func testHeadingSlugs() {
        // Spaces become hyphens, punctuation is stripped, case is lowered.
        XCTAssertEqual(
            MarkdownRenderer.render("## Getting Started").html,
            "<h2 id=\"getting-started\">Getting Started</h2>"
        )
        XCTAssertEqual(
            MarkdownRenderer.render("## What's New?").html,
            "<h2 id=\"whats-new\">What&#39;s New?</h2>"
        )
        // Duplicate headings get -1, -2 suffixes.
        let dup = MarkdownRenderer.render("# Intro\n\n# Intro\n\n# Intro").html
        XCTAssertTrue(dup.contains("<h1 id=\"intro\">Intro</h1>"))
        XCTAssertTrue(dup.contains("<h1 id=\"intro-1\">Intro</h1>"))
        XCTAssertTrue(dup.contains("<h1 id=\"intro-2\">Intro</h1>"))
        // Unicode letters survive.
        XCTAssertEqual(
            MarkdownRenderer.render("## Café Münchner").html,
            "<h2 id=\"café-münchner\">Café Münchner</h2>"
        )
        // Stripped punctuation surrounded by whitespace leaves consecutive
        // whitespace that maps to consecutive hyphens — matching GitHub's
        // slug algorithm. `\s+ -> -` would collapse runs and break links
        // generated by GitHub-style TOC tools. (PR #10, @ReubenCowell.)
        XCTAssertEqual(
            MarkdownRenderer.render("## Intro to Programming — Spec Points").html,
            "<h2 id=\"intro-to-programming--spec-points\">Intro to Programming — Spec Points</h2>"
        )
    }

    // MARK: - Emphasis

    func testBold() {
        XCTAssertEqual(MarkdownRenderer.render("**bold**").html, "<p><strong>bold</strong></p>")
        XCTAssertEqual(MarkdownRenderer.render("__bold__").html, "<p><strong>bold</strong></p>")
    }

    func testItalic() {
        XCTAssertEqual(MarkdownRenderer.render("*italic*").html, "<p><em>italic</em></p>")
        XCTAssertEqual(MarkdownRenderer.render("_italic_").html, "<p><em>italic</em></p>")
    }

    func testBoldItalic() {
        XCTAssertEqual(MarkdownRenderer.render("***both***").html, "<p><strong><em>both</em></strong></p>")
    }

    func testStrikethrough() {
        XCTAssertEqual(MarkdownRenderer.render("~~deleted~~").html, "<p><del>deleted</del></p>")
    }

    // MARK: - Code

    func testInlineCode() {
        XCTAssertEqual(MarkdownRenderer.render("`code`").html, "<p><code>code</code></p>")
    }

    func testUnderscoresInCodeSpanAreNotEmphasis() {
        // Issue #6: the emphasis passes reached inside code spans and ate
        // underscores (turning them into <em>). Code span content must render
        // verbatim per CommonMark — including across two code spans in one
        // paragraph, which is what the original report hit.
        let twoLines = MarkdownRenderer.render(
            "This is test `test_text.md`\nAnother line `~/test_text.md`").html
        XCTAssertTrue(twoLines.contains("<code>test_text.md</code>"))
        XCTAssertTrue(twoLines.contains("<code>~/test_text.md</code>"))
        XCTAssertFalse(twoLines.contains("<em>"))

        XCTAssertEqual(MarkdownRenderer.render("`a_b_c`").html, "<p><code>a_b_c</code></p>")
        XCTAssertEqual(MarkdownRenderer.render("`a*b*c`").html, "<p><code>a*b*c</code></p>")
    }

    func testHtmlTagsInCodeSpanAreLiteral() {
        // Code span content must be fully verbatim — HTML tags inside it render
        // as escaped text, not real markup.
        XCTAssertEqual(MarkdownRenderer.render("`<div>`").html, "<p><code>&lt;div&gt;</code></p>")
        let em = MarkdownRenderer.render("`<em>hi</em>`").html
        XCTAssertTrue(em.contains("<code>&lt;em&gt;hi&lt;/em&gt;</code>"))
        XCTAssertFalse(em.contains("<em>"))
    }

    func testFencedCodeBlock() {
        let md = "```swift\nlet x = 1\n```"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("<pre><code class=\"language-swift\">"))
        XCTAssertTrue(result.contains("let x = 1"))
    }

    func testFencedCodeBlockNoLanguage() {
        let md = "```\nplain code\n```"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("<pre><code>"))
        XCTAssertFalse(result.contains("nohighlight"))
        XCTAssertTrue(result.contains("plain code"))
    }

    func testCodeBlockEscapesHTML() {
        let md = "```\n<div>test</div>\n```"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("&lt;div&gt;"))
    }

    // MARK: - Links and Images

    func testLink() {
        let result = MarkdownRenderer.render("[Click](https://example.com)").html
        XCTAssertEqual(result, "<p><a href=\"https://example.com\">Click</a></p>")
    }

    func testImage() {
        let result = MarkdownRenderer.render("![Alt](https://example.com/img.png)").html
        XCTAssertEqual(result, "<p><img src=\"https://example.com/img.png\" alt=\"Alt\"></p>")
    }

    func testMailtoLink() {
        let result = MarkdownRenderer.render("[Email](mailto:test@example.com)").html
        XCTAssertTrue(result.contains("href=\"mailto:test@example.com\""))
    }

    func testAnchorLink() {
        let result = MarkdownRenderer.render("[Section](#section)").html
        XCTAssertTrue(result.contains("href=\"#section\""))
    }

    // MARK: - URL Safety

    func testJavascriptURLBlocked() {
        let result = MarkdownRenderer.render("[xss](javascript:alert(1))").html
        XCTAssertFalse(result.contains("href"))
        XCTAssertFalse(result.contains("javascript"))
    }

    func testDataURLBlocked() {
        let result = MarkdownRenderer.render("[xss](data:text/html,<script>alert(1)</script>)").html
        XCTAssertFalse(result.contains("href"))
    }

    func testProtocolRelativeURLBlocked() {
        let result = MarkdownRenderer.render("[xss](//evil.com)").html
        XCTAssertFalse(result.contains("href"))
    }

    func testSafeURLsAllowed() {
        let httpResult = MarkdownRenderer.render("[ok](https://example.com)").html
        XCTAssertTrue(httpResult.contains("href"))

        let relativeResult = MarkdownRenderer.render("[ok](./file.md)").html
        XCTAssertTrue(relativeResult.contains("href"))
    }

    // MARK: - Lists

    func testUnorderedList() {
        let md = "- one\n- two\n- three"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("<ul>"))
        XCTAssertTrue(result.contains("<li>one</li>"))
        XCTAssertTrue(result.contains("<li>two</li>"))
        XCTAssertTrue(result.contains("<li>three</li>"))
    }

    func testNestedUnorderedList() {
        // A nested list was emitted as a sibling <ul> of the parent <li>
        // (invalid HTML). It must render *inside* the parent <li>.
        let basic = MarkdownRenderer.render("- parent\n  - child").html
        XCTAssertEqual(basic, "<ul><li>parent<ul><li>child</li></ul></li></ul>")
        XCTAssertFalse(basic.contains("</li><ul>"))

        // A top-level item after a nested run stays a sibling of the right <li>.
        let mixed = MarkdownRenderer.render("- a\n  - a1\n- b").html
        XCTAssertEqual(mixed, "<ul><li>a<ul><li>a1</li></ul></li><li>b</li></ul>")
    }

    func testBoldDoesNotLeakAcrossListItemsWhenCodeSpansContainHTMLTags() {
        //  regression: a bullet whose code spans contained `<strong>`
        // and `<em>` (real HTML tag names) used to leak those tags through and
        // turn every following <li> bold via the parser's active-formatting list.
        let md = """
        **Apply when (setting):**

        - Don't wrap `b3nd` in `<strong>`, `<em>`, `**…**`, `*…*`, or any equivalent.
        - Don't ship bold/italic cuts of the logo font. One face, one weight.
        - Don't let surrounding context cascade into the word — `<b-3>` resets by default.
        """
        let html = MarkdownRenderer.render(md).html

        XCTAssertTrue(html.contains("<strong>Apply when (setting):</strong>"))
        // The bullets must not be wrapped in <strong>.
        XCTAssertFalse(html.contains("<strong>Don't ship"))
        XCTAssertFalse(html.contains("<strong>Don't let"))
        // The HTML-tag code spans must render as escaped literal text.
        XCTAssertTrue(html.contains("<code>&lt;strong&gt;</code>"))
        XCTAssertTrue(html.contains("<code>&lt;em&gt;</code>"))
        // And there must be no unbalanced/raw <strong> or <em> outside <code>.
        XCTAssertFalse(html.contains("<code><strong>"))
        XCTAssertFalse(html.contains("<code><em>"))
    }

    func testOrderedList() {
        let md = "1. first\n2. second"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("<ol>"))
        XCTAssertTrue(result.contains("<li>first</li>"))
        XCTAssertTrue(result.contains("<li>second</li>"))
    }

    func testTaskList() {
        let md = "- [ ] todo\n- [x] done"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("task-list"))
        XCTAssertTrue(result.contains("checkbox\" disabled"))
        XCTAssertTrue(result.contains("checkbox\" checked disabled"))
    }

    func testListItemContinuationFlows() {
        let md = "- first item that wraps\n  onto a second source line\n- second item"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("<li>first item that wraps onto a second source line</li>"))
        XCTAssertFalse(result.contains("<br>"))
    }

    // MARK: - Code Inside Lists (issue #9)

    /// troelskn's exact repro from issue #9. Indented fence under an ordered
    /// list item must render as a real code block, not collapsed into prose.
    func testFencedCodeInsideOrderedListItem() {
        let md = """
        1. Lorem ipsum dolor sit amet:
           ```bash
           bin/foobar --yoinks
           ```
        2. Bish bash bosh:
           ```bash
           bin/foobar --yoinks
           ```
        """
        let html = MarkdownRenderer.render(md).html
        // Each item carries its own real <pre><code class="language-bash"> block.
        let preCount = html.components(separatedBy: "<pre><code class=\"language-bash\">").count - 1
        XCTAssertEqual(preCount, 2, "Both list items should contain a fenced code block")
        XCTAssertTrue(html.contains("bin/foobar --yoinks"))
        // Negative: the fence backticks must not leak as literal text.
        XCTAssertFalse(html.contains("```bash"), "Raw fence should not appear as text")
    }

    /// Same flow under an unordered list — covers the shared continuation helper.
    func testFencedCodeInsideUnorderedListItem() {
        let md = """
        - intro line
          ```swift
          let x = 1
          ```
        - next item
        """
        let html = MarkdownRenderer.render(md).html
        XCTAssertTrue(html.contains("<pre><code class=\"language-swift\">let x = 1</code></pre>"))
        XCTAssertTrue(html.contains("<li>next item</li>"))
    }

    /// A bare (no-language) fence inside a list item still renders as a code block.
    func testBareFencedCodeInsideListItem() {
        let md = """
        - prefix
          ```
          plain code
          ```
        """
        let html = MarkdownRenderer.render(md).html
        XCTAssertTrue(html.contains("<pre><code>plain code</code></pre>"))
    }

    /// An unclosed fence inside a list item consumes to end-of-input rather than
    /// leaving the renderer in a bad state.
    func testUnclosedFencedCodeInsideListItemConsumesToEOF() {
        let md = """
        - start
          ```bash
          oops no close
        """
        let html = MarkdownRenderer.render(md).html
        XCTAssertTrue(html.contains("<pre><code class=\"language-bash\">"))
        XCTAssertTrue(html.contains("oops no close"))
    }

    // MARK: - Line breaks

    func testSoftNewlineBecomesSpace() {
        let result = MarkdownRenderer.render("line one\nline two").html
        XCTAssertEqual(result, "<p>line one line two</p>")
    }

    func testHardBreakWithTwoTrailingSpaces() {
        let result = MarkdownRenderer.render("line one  \nline two").html
        XCTAssertEqual(result, "<p>line one<br>line two</p>")
    }

    // MARK: - Blockquote

    func testBlockquote() {
        let result = MarkdownRenderer.render("> quoted text").html
        XCTAssertTrue(result.contains("<blockquote>"))
        XCTAssertTrue(result.contains("quoted text"))
    }

    // MARK: - Horizontal Rule

    func testHorizontalRule() {
        XCTAssertEqual(MarkdownRenderer.render("---").html, "<hr>")
        XCTAssertEqual(MarkdownRenderer.render("***").html, "<hr>")
        XCTAssertEqual(MarkdownRenderer.render("___").html, "<hr>")
    }

    func testHorizontalRuleNeedsThreeChars() {
        let result = MarkdownRenderer.render("--").html
        XCTAssertFalse(result.contains("<hr>"))
    }

    // MARK: - Setext Headings

    func testSetextH1() {
        XCTAssertEqual(MarkdownRenderer.render("Title\n===").html, "<h1 id=\"title\">Title</h1>")
    }

    func testSetextH2() {
        XCTAssertEqual(MarkdownRenderer.render("Title\n---").html, "<h2 id=\"title\">Title</h2>")
    }

    // A `---` with no preceding paragraph line stays a thematic break.
    func testDashesAloneAreHorizontalRule() {
        XCTAssertEqual(MarkdownRenderer.render("---").html, "<hr>")
        XCTAssertEqual(MarkdownRenderer.render("\n---").html, "<hr>")
    }

    func testSetextWithInlineFormatting() {
        XCTAssertEqual(
            MarkdownRenderer.render("**Bold** title\n===").html,
            "<h1 id=\"bold-title\"><strong>Bold</strong> title</h1>"
        )
    }

    // MARK: - Tables

    func testTable() {
        let md = "| A | B |\n| --- | --- |\n| 1 | 2 |"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("<table>"))
        XCTAssertTrue(result.contains("<th"))
        XCTAssertTrue(result.contains("<td"))
        XCTAssertTrue(result.contains("A"))
        XCTAssertTrue(result.contains("1"))
    }

    func testTableAlignment() {
        let md = "| Left | Center | Right |\n| :--- | :---: | ---: |\n| a | b | c |"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("align=\"left\""))
        XCTAssertTrue(result.contains("align=\"center\""))
        XCTAssertTrue(result.contains("align=\"right\""))
    }

    // MARK: - HTML Passthrough

    func testHTMLPassthrough() {
        let md = "<div>raw html</div>"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("<div>raw html</div>"))
    }

    func testScriptTagInInlineCodeDoesNotBreakPreview() {
        // Issue #3: Literal `<script>` inside a code span used to be preserved as a real tag,
        // causing the browser to swallow everything after it as script source.
        let result = MarkdownRenderer.render("Add a `<script>` tag").html
        XCTAssertTrue(result.contains("<code>&lt;script&gt;</code>"))
        XCTAssertFalse(result.contains("<code><script>"))
    }

    func testBareScriptTagIsEscaped() {
        let result = MarkdownRenderer.render("<script>alert(1)</script>").html
        XCTAssertTrue(result.contains("&lt;script&gt;"))
        XCTAssertFalse(result.contains("<script>"))
    }

    func testHTMLEntitiesPassThrough() {
        // Issue #4: Valid HTML entities (named, decimal, hex) render as their character.
        let result = MarkdownRenderer.render("Copyright &copy; 2025 &ndash; &#169; &#xA9;").html
        XCTAssertTrue(result.contains("&copy;"))
        XCTAssertTrue(result.contains("&ndash;"))
        XCTAssertTrue(result.contains("&#169;"))
        XCTAssertTrue(result.contains("&#xA9;"))
        XCTAssertFalse(result.contains("&amp;copy;"))
    }

    func testStrayAmpersandStillEscaped() {
        // Not a valid entity — must still be escaped to avoid malformed HTML.
        let result = MarkdownRenderer.render("Tom & Jerry").html
        XCTAssertTrue(result.contains("Tom &amp; Jerry"))
    }

    func testHTMLCommentPreserved() {
        let result = MarkdownRenderer.render("Before <!-- hidden --> after").html
        XCTAssertTrue(result.contains("<!-- hidden -->"))
        XCTAssertFalse(result.contains("&lt;!--"))
    }

    // MARK: - HTML sanitization (allowlist)

    func testBlockLevelScriptIsEscaped() {
        // Regression: a <script> nested in a block-level tag used to bypass the
        // inline escaper (block path only stripped attributes) and execute.
        let result = MarkdownRenderer.render("<div><script>alert(1)</script></div>").html
        XCTAssertTrue(result.contains("&lt;script&gt;"))
        XCTAssertFalse(result.contains("<script>"))
    }

    func testEventHandlerWithoutLeadingSpaceIsStripped() {
        // `"x"onerror=` has no whitespace before the handler; the old regex missed it.
        let result = MarkdownRenderer.render("<img src=\"x\"onerror=\"alert(1)\">").html
        XCTAssertFalse(result.lowercased().contains("onerror"))
        XCTAssertTrue(result.contains("<img"))
    }

    func testEventHandlerWithSpaceIsStripped() {
        let result = MarkdownRenderer.render("<a href=\"#\" onclick=\"steal()\">x</a>").html
        XCTAssertFalse(result.lowercased().contains("onclick"))
        XCTAssertTrue(result.contains("href=\"#\""))
    }

    func testDangerousTagsAreEscaped() {
        for tag in ["<iframe src=\"x\">", "<style>body{}</style>", "<base href=\"//evil\">",
                    "<meta http-equiv=\"refresh\">", "<link rel=\"x\">", "<svg onload=\"alert(1)\">",
                    "<object data=\"x\">", "<form action=\"x\">"] {
            let result = MarkdownRenderer.render(tag).html
            XCTAssertTrue(result.contains("&lt;"), "\(tag) should be escaped to text")
        }
    }

    func testSafeInlineHTMLStillPasses() {
        let result = MarkdownRenderer.render("A <span class=\"hl\">x</span>, <kbd>Cmd</kbd>, <br> end").html
        XCTAssertTrue(result.contains("<span class=\"hl\">"))
        XCTAssertTrue(result.contains("<kbd>"))
        XCTAssertTrue(result.contains("<br>"))
    }

    /// `<center>` is a safe presentational tag that worked before the allowlist
    /// hardening; it must keep passing through so centered documents still render.
    func testCenterTagPassesThrough() {
        let result = MarkdownRenderer.render("<center>middle</center>").html
        XCTAssertTrue(result.contains("<center>middle</center>"))
    }

    func testUnsafeAttributesDroppedSafeKept() {
        let result = MarkdownRenderer.render("<div class=\"ok\" style=\"x\" onmouseover=\"y\">z</div>").html
        XCTAssertTrue(result.contains("class=\"ok\""))
        XCTAssertFalse(result.lowercased().contains("onmouseover"))
        XCTAssertFalse(result.contains("style="))
    }

    func testScriptContentIsOpaque() {
        // A tag nested inside an (escaped) <script> must not leak as real markup.
        let result = MarkdownRenderer.render("<div><script>x=1;<h2>LEAK</h2></script></div>").html
        XCTAssertFalse(result.contains("<h2>"), "script content must be opaque, not rendered")
        XCTAssertTrue(result.contains("&lt;h2&gt;"))
    }

    // MARK: - Backslash escapes

    func testBackslashEscapesEmphasis() {
        XCTAssertEqual(MarkdownRenderer.render("\\*not italic\\*").html, "<p>*not italic*</p>")
        XCTAssertEqual(MarkdownRenderer.render("a\\_b\\_c").html, "<p>a_b_c</p>")
    }

    func testBackslashEscapesBlockStarters() {
        XCTAssertEqual(MarkdownRenderer.render("\\# not a heading").html, "<p># not a heading</p>")
        XCTAssertEqual(MarkdownRenderer.render("\\- not a list").html, "<p>- not a list</p>")
    }

    func testBackslashEscapesBracketsAndAngle() {
        // Inline escaped brackets. (A whole line of `\[…\]` is display math by
        // design — see the math tests — so this uses mid-line brackets.)
        XCTAssertEqual(MarkdownRenderer.render("see \\[1\\] here").html, "<p>see [1] here</p>")
        XCTAssertEqual(MarkdownRenderer.render("less than \\< here").html, "<p>less than &lt; here</p>")
    }

    func testBackslashInsideCodeSpanIsLiteral() {
        // CommonMark: backslash escapes don't apply inside code spans.
        XCTAssertEqual(MarkdownRenderer.render("`a\\*b`").html, "<p><code>a\\*b</code></p>")
    }

    func testBackslashBeforeNonPunctuationIsLiteral() {
        // `\n` (backslash + letter) is a literal backslash, not an escape.
        XCTAssertEqual(MarkdownRenderer.render("path C:\\next").html, "<p>path C:\\next</p>")
    }

    func testEscapedDollarStillNotMath() {
        // The `$`-specific escape path must keep working alongside general escapes.
        XCTAssertEqual(MarkdownRenderer.render("costs \\$5 today").html, "<p>costs $5 today</p>")
    }

    func testRawHTMLDangerousURLSchemesDropped() {
        let a = MarkdownRenderer.render("<a href=\"javascript:alert(1)\">x</a>").html
        XCTAssertFalse(a.lowercased().contains("javascript:"))
        XCTAssertTrue(a.contains("<a"))
        let img = MarkdownRenderer.render("<img src=\"javascript:alert(1)\">").html
        XCTAssertFalse(img.lowercased().contains("javascript:"))
        let safe = MarkdownRenderer.render("<a href=\"https://example.com\">x</a>").html
        XCTAssertTrue(safe.contains("href=\"https://example.com\""))
    }

    func testTableSwallowsAdjacentPipeLine() {
        // GitHub-style leniency: a pipe line right after a table (no blank line) is
        // another row. Pinned to match GitHub — separate with a blank line to end it.
        let md = "| A | B |\n|---|---|\n| 1 | 2 |\nprose | with pipe"
        XCTAssertTrue(MarkdownRenderer.render(md).html.contains("<td align=\"left\">prose</td>"))
    }

    // MARK: - Links

    func testLinkURLWithParens() {
        // e.g. Wikipedia links like /wiki/Foo_(bar). Underscore is entity-encoded in the href
        // so the later italic regex pass (`_..._`) can't corrupt the attribute.
        let result = MarkdownRenderer.render("[Wiki](https://en.wikipedia.org/wiki/Foo_(bar))").html
        XCTAssertTrue(result.contains("<a href=\"https://en.wikipedia.org/wiki/Foo&#95;(bar)\">Wiki</a>"))
        XCTAssertFalse(result.contains("<em>"))
    }

    func testAutolinkURL() {
        let result = MarkdownRenderer.render("Visit <https://example.com> today").html
        XCTAssertTrue(result.contains("<a href=\"https://example.com\">https://example.com</a>"))
    }

    func testAutolinkEmail() {
        let result = MarkdownRenderer.render("Email <hi@example.com> please").html
        XCTAssertTrue(result.contains("<a href=\"mailto:hi@example.com\">hi@example.com</a>"))
    }

    func testAutolinkRejectsUnsafeScheme() {
        // javascript: or other non-http schemes must not become clickable links.
        let result = MarkdownRenderer.render("<javascript:alert(1)>").html
        XCTAssertFalse(result.contains("<a href=\"javascript:"))
    }

    // MARK: - HTML Escaping

    func testHTMLEscaping() {
        XCTAssertEqual(MarkdownRenderer.escapeHTML("<script>"), "&lt;script&gt;")
        XCTAssertEqual(MarkdownRenderer.escapeHTML("a & b"), "a &amp; b")
        XCTAssertEqual(MarkdownRenderer.escapeHTML("\"quoted\""), "&quot;quoted&quot;")
    }

    func testParagraphPreservesInlineHTML() {
        let result = MarkdownRenderer.render("Hello <em>world</em>").html
        XCTAssertTrue(result.contains("<em>world</em>"))
    }

    func testCodeBlockEscapesAllHTML() {
        let md = "```\n<script>alert(1)</script>\n```"
        let result = MarkdownRenderer.render(md).html
        XCTAssertFalse(result.contains("<script>"))
        XCTAssertTrue(result.contains("&lt;script&gt;"))
    }

    // MARK: - Mermaid

    func testMermaidBlockUsesMermaidClass() {
        let md = "```mermaid\ngraph TD\n    A-->B\n```"
        let result = MarkdownRenderer.render(md)
        XCTAssertTrue(result.html.contains("<pre class=\"mermaid\">"))
        XCTAssertFalse(result.html.contains("<code"))
        XCTAssertTrue(result.hasMermaid)
    }

    func testMermaidBlockNotEscaped() {
        let md = "```mermaid\ngraph TD\n    A-->B\n```"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("A-->B"))
        XCTAssertFalse(result.contains("&gt;"))
    }

    func testMermaidCaseInsensitive() {
        let md = "```Mermaid\ngraph TD\n    A-->B\n```"
        let result = MarkdownRenderer.render(md)
        XCTAssertTrue(result.html.contains("<pre class=\"mermaid\">"))
        XCTAssertTrue(result.hasMermaid)
    }

    func testNoMermaidFlagForRegularCode() {
        let md = "```swift\nlet x = 1\n```"
        let result = MarkdownRenderer.render(md)
        XCTAssertFalse(result.hasMermaid)
    }

    // MARK: - Math (TeX)

    func testInlineDollarMath() {
        let result = MarkdownRenderer.render("Euler: $e^{i\\pi}+1=0$ done")
        XCTAssertTrue(result.html.contains("<span class=\"rd-math rd-math-inline\">e^{i\\pi}+1=0</span>"))
        XCTAssertTrue(result.hasMath)
        XCTAssertFalse(result.hasMermaid)
    }

    func testInlineParenMath() {
        let result = MarkdownRenderer.render("Inline \\(x^2\\) here")
        XCTAssertTrue(result.html.contains("<span class=\"rd-math rd-math-inline\">x^2</span>"))
        XCTAssertTrue(result.hasMath)
    }

    func testDisplayDollarMathSingleLine() {
        let result = MarkdownRenderer.render("$$\\int_0^1 x\\,dx$$")
        XCTAssertTrue(result.html.contains("<div class=\"rd-math rd-math-display\">\\int_0^1 x\\,dx</div>"))
        XCTAssertTrue(result.hasMath)
    }

    func testDisplayMathMultiLine() {
        let result = MarkdownRenderer.render("$$\nx = y\n+ z\n$$").html
        XCTAssertTrue(result.contains("<div class=\"rd-math rd-math-display\">x = y\n+ z</div>"))
    }

    func testDisplayBracketMath() {
        let result = MarkdownRenderer.render("\\[ a^2 + b^2 \\]").html
        XCTAssertTrue(result.contains("<div class=\"rd-math rd-math-display\">a^2 + b^2</div>"))
    }

    /// Markdown delimiters inside math are part of the TeX, not formatting — the
    /// span is stashed before any emphasis/escape pass runs.
    func testMathProtectedFromInlineMarkdown() {
        let underscores = MarkdownRenderer.render("$a_i + b_j$").html
        XCTAssertTrue(underscores.contains("a_i + b_j"))
        XCTAssertFalse(underscores.contains("<em>"))

        let stars = MarkdownRenderer.render("$a * b * c$").html
        XCTAssertTrue(stars.contains("<span class=\"rd-math rd-math-inline\">a * b * c</span>"))
        XCTAssertFalse(stars.contains("<strong>"))
        XCTAssertFalse(stars.contains("<em>"))
    }

    /// `<`, `>`, `&` in TeX are HTML-escaped so the markup is valid; the browser
    /// decodes them back via `textContent` before KaTeX parses the source.
    func testMathHTMLEscaped() {
        let result = MarkdownRenderer.render("$a < b & c$").html
        XCTAssertTrue(result.contains("a &lt; b &amp; c"))
        XCTAssertFalse(result.contains("a < b"))
    }

    /// A code span wins over math: `` `$x$` `` is literal code, not an equation.
    func testCodeSpanBeatsMath() {
        let result = MarkdownRenderer.render("Use `$x$` in code")
        XCTAssertTrue(result.html.contains("<code>$x$</code>"))
        XCTAssertFalse(result.hasMath)
    }

    /// A fenced code block containing `$$` stays literal — fences are matched
    /// before the display-math block.
    func testFenceBeatsDisplayMath() {
        let result = MarkdownRenderer.render("```\n$$not math$$\n```")
        XCTAssertTrue(result.html.contains("<pre><code>"))
        XCTAssertTrue(result.html.contains("$$not math$$"))
        XCTAssertFalse(result.hasMath)
    }

    /// Dollar amounts in prose must not be parsed as inline math.
    func testDollarAmountsAreNotMath() {
        let result = MarkdownRenderer.render("It cost $5 and then $10 total")
        XCTAssertFalse(result.hasMath)
        XCTAssertFalse(result.html.contains("rd-math"))
    }

    /// `$5:$x$` must not parse `$5:` as a math span — a digit immediately after
    /// the opening `$` signals currency, not TeX.
    func testDollarBeforeDigitIsNotMath() {
        let result = MarkdownRenderer.render("It cost $5:$x$ is odd notation")
        XCTAssertFalse(result.html.contains(">5:<"))
    }

    /// `\$` is an escaped literal dollar and never opens a math span.
    func testEscapedDollarIsLiteral() {
        let result = MarkdownRenderer.render("Price is \\$5 today")
        XCTAssertTrue(result.html.contains("Price is $5 today"))
        XCTAssertFalse(result.hasMath)
    }

    /// A display block immediately after a paragraph (no blank line) still splits
    /// off instead of being absorbed as prose.
    func testDisplayMathSplitsFromParagraph() {
        let result = MarkdownRenderer.render("Some text\n$$x^2$$").html
        XCTAssertTrue(result.contains("<p>Some text</p>"))
        XCTAssertTrue(result.contains("rd-math-display"))
    }

    /// Math nested in a blockquote bubbles `hasMath` up through the recursive render.
    func testMathInBlockquoteSetsHasMath() {
        let result = MarkdownRenderer.render("> Euler $e^{i\\pi}=-1$")
        XCTAssertTrue(result.hasMath)
        XCTAssertTrue(result.html.contains("rd-math-inline"))
    }

    func testNoMathFlagForPlainText() {
        XCTAssertFalse(MarkdownRenderer.render("just regular **prose** here").hasMath)
    }

    /// A line beginning with `$$` but with no closing `$$` on the same line and
    /// content after the opener must NOT be treated as display math — it's prose.
    /// Regression test for the "$$5 million eats subsequent lines" bug.
    func testDoubleDollarInProseIsNotDisplayMath() {
        let result = MarkdownRenderer.render("Revenue was $$5 million\nNext line of prose")
        XCTAssertFalse(result.hasMath)
        XCTAssertTrue(result.html.contains("$$5 million"))
        XCTAssertTrue(result.html.contains("Next line of prose"))
    }

    /// A line beginning with `\[` but with no `\]` on the same line must NOT
    /// trigger a display-math block when the content looks like prose.
    /// Regression test for the "\[RFC 1234] eats subsequent lines" bug.
    func testBackslashBracketInProseIsNotDisplayMath() {
        let result = MarkdownRenderer.render("See \\[RFC 1234] for details\nNext paragraph")
        XCTAssertFalse(result.hasMath)
        XCTAssertTrue(result.html.contains("Next paragraph"))
    }

    // MARK: - Tilde Fences

    func testTildeFenceWithLanguage() {
        let md = "~~~ruby\nputs 'hi'\n~~~"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("<pre><code class=\"language-ruby\">"))
        XCTAssertTrue(result.contains("puts &#39;hi&#39;"))
    }

    func testTildeFenceNoLanguage() {
        let md = "~~~\nplain\n~~~"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("<pre><code>"))
        XCTAssertFalse(result.contains("nohighlight"))
    }

    func testUnclosedCodeBlock() {
        let md = "```\nno closing fence\nstill going"
        let result = MarkdownRenderer.render(md).html
        XCTAssertTrue(result.contains("<pre><code"))
        XCTAssertTrue(result.contains("no closing fence"))
        XCTAssertTrue(result.contains("still going"))
    }

    // MARK: - Inline Replacement Edge Cases

    func testMultipleInlinePatternsOnOneLine() {
        let result = MarkdownRenderer.render("**bold** and *italic* and `code` and [link](https://x.com)").html
        XCTAssertTrue(result.contains("<strong>bold</strong>"))
        XCTAssertTrue(result.contains("<em>italic</em>"))
        XCTAssertTrue(result.contains("<code>code</code>"))
        XCTAssertTrue(result.contains("<a href=\"https://x.com\">link</a>"))
    }

    func testMultipleLinksOnOneLine() {
        let result = MarkdownRenderer.render("[a](https://a.com) and [b](https://b.com)").html
        XCTAssertTrue(result.contains("href=\"https://a.com\""))
        XCTAssertTrue(result.contains("href=\"https://b.com\""))
    }

    func testMultipleBoldOnOneLine() {
        let result = MarkdownRenderer.render("**one** then **two** then **three**").html
        let count = result.components(separatedBy: "<strong>").count - 1
        XCTAssertEqual(count, 3)
    }

    func testEmojiInParagraph() {
        let result = MarkdownRenderer.render("Hello 🎉 world 🚀").html
        XCTAssertTrue(result.contains("🎉"))
        XCTAssertTrue(result.contains("🚀"))
    }

    func testUnicodeInBold() {
        let result = MarkdownRenderer.render("**café** and *naïve*").html
        XCTAssertTrue(result.contains("<strong>café</strong>"))
        XCTAssertTrue(result.contains("<em>naïve</em>"))
    }

    func testSnakeCaseNotItalicized() {
        let result = MarkdownRenderer.render("use my_var here").html
        XCTAssertTrue(result.contains("my_var"))
    }

    func testLinkWithSpecialCharsInURL() {
        let result = MarkdownRenderer.render("[search](https://google.com/search?q=hello&lang=en)").html
        XCTAssertTrue(result.contains("href=\"https://google.com/search?q=hello&amp;lang=en\""))
    }

    // MARK: - Empty / Edge Cases

    func testEmptyInput() {
        XCTAssertEqual(MarkdownRenderer.render("").html, "")
    }

    func testBlankLines() {
        XCTAssertEqual(MarkdownRenderer.render("\n\n\n").html, "")
    }

    // MARK: - Renderer Safety (no-advance / hang resistance — issue #8)

    /// A line beginning with `#` followed by a non-space character isn't a heading
    /// (per CommonMark and `headingPattern`). Earlier, the paragraph collector
    /// rejected it on a bare `hasPrefix("#")` check and `i` never advanced —
    /// hanging the renderer. Regression test for issue #8.
    func testParagraphLineStartingWithHashNumberDoesNotHang() {
        let input = """
        # test

        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
        Ipsum has been the industry's standard dummy text ever since 1966, when designers
        at Letraset and James Mosley, the librarian at St Bride Printing Library, took a
        1914 Cicero translation and scrambled it to make dummy text for Letraset's Body
        #24 Type sheets. It has survived not only many decades, but also the leap into
        electronic typesetting, remaining essentially unchanged.
        """
        // If this returns at all (i.e. doesn't hang the test runner), the
        // no-advance bug is fixed. Then verify the content is collected as
        // a single paragraph with `#24 Type sheets` preserved inline.
        let html = MarkdownRenderer.render(input).html
        XCTAssertTrue(html.contains("<h1 id=\"test\">test</h1>"))
        XCTAssertTrue(html.contains("#24 Type sheets"),
                      "Line beginning with `#24` should be paragraph content, not split off")
        XCTAssertTrue(html.contains("<p>") && html.contains("</p>"))
    }

    /// A standalone line consisting only of `#` followed by digits is a paragraph,
    /// not a heading. Must not hang.
    func testStandaloneHashNumberIsParagraph() {
        let html = MarkdownRenderer.render("#24").html
        XCTAssertEqual(html, "<p>#24</p>")
    }

    /// `#` followed immediately by non-space, non-digit characters (e.g. a hyphen,
    /// a letter run with no space) is also not a heading.
    func testHashWithoutSpaceFollowedByLetterIsParagraph() {
        XCTAssertEqual(MarkdownRenderer.render("#hashtag").html, "<p>#hashtag</p>")
        XCTAssertEqual(MarkdownRenderer.render("#-foo").html, "<p>#-foo</p>")
    }

    /// A lone `#` on a line IS a heading (empty title) per `headingPattern`'s
    /// `(?:\s+|$)` alternative. Confirms we didn't accidentally narrow the
    /// heading recognizer along with fixing the paragraph collector.
    func testLoneHashIsEmptyHeading() {
        XCTAssertEqual(MarkdownRenderer.render("#").html, "<h1 id=\"section\"></h1>")
    }

    // MARK: - Underscore emphasis flanking (CommonMark §6.2)

    /// Single underscores inside words are literal, not italic delimiters.
    /// Regression caught while QA-ing 1.14 against `stress-large.md` §7.
    func testIntraWordUnderscoresAreNotItalic() {
        let html = MarkdownRenderer.render("lots_of_underscores_in_names").html
        XCTAssertFalse(html.contains("<em>"), "Intra-word `_` must not italicize")
        XCTAssertTrue(html.contains("lots_of_underscores_in_names"))
    }

    /// Same rule for `__double__` inside a word — no bold.
    func testIntraWordDoubleUnderscoresAreNotBold() {
        let html = MarkdownRenderer.render("some__double__underscores").html
        XCTAssertFalse(html.contains("<strong>"), "Intra-word `__` must not bold")
        XCTAssertTrue(html.contains("some__double__underscores"))
    }

    /// Standalone `_word_` still italicizes — we only added flanking, not removed emphasis.
    func testStandaloneUnderscoreItalicStillWorks() {
        XCTAssertEqual(MarkdownRenderer.render("_italic_").html, "<p><em>italic</em></p>")
    }

    /// Standalone `__word__` still bolds.
    func testStandaloneDoubleUnderscoreBoldStillWorks() {
        XCTAssertEqual(MarkdownRenderer.render("__bold__").html, "<p><strong>bold</strong></p>")
    }

    /// Punctuation counts as a non-word boundary, so `(_x_)` italicizes.
    func testUnderscoreItalicFlanksPunctuation() {
        let html = MarkdownRenderer.render("(_x_)").html
        XCTAssertTrue(html.contains("<em>x</em>"))
    }

    /// Unicode letters block flanking too — Cyrillic identifier stays literal.
    func testUnderscoreFlankingRespectsUnicodeLetters() {
        let html = MarkdownRenderer.render("мир_слов_здесь").html
        XCTAssertFalse(html.contains("<em>"))
    }

    /// `snake_case` (single underscore, both sides letters) already failed to match
    /// the pre-fix regex (needs two `_`s); confirm it stays literal post-fix too.
    func testSnakeCaseStaysLiteral() {
        let html = MarkdownRenderer.render("Use snake_case for variables").html
        XCTAssertFalse(html.contains("<em>"))
        XCTAssertTrue(html.contains("snake_case"))
    }

    // MARK: - HTML Template integration (Mermaid theming, 1.14)

    /// The Mermaid-bearing HTML must carry `data-rd-theme` so the JS init script
    /// can resolve the theme deterministically. Verifies the Swift→HTML→JS
    /// pipeline emits both halves correctly.
    func testMermaidHTMLCarriesThemeAttribute() {
        let md = """
        # x

        ```mermaid
        flowchart TD
          A[Start] --> B[End]
        ```
        """
        let renderResult = MarkdownRenderer.render(md)
        XCTAssertTrue(renderResult.hasMermaid)

        let darkHTML = HTMLTemplate.wrap(body: renderResult.html, hasMermaid: true, isDark: true)
        XCTAssertTrue(darkHTML.contains("data-rd-theme=\"dark\""))
        XCTAssertTrue(darkHTML.contains("dataset.rdTheme"))
        XCTAssertTrue(darkHTML.contains("dark ? 'dark' : 'default'"))

        let lightHTML = HTMLTemplate.wrap(body: renderResult.html, hasMermaid: true, isDark: false)
        XCTAssertTrue(lightHTML.contains("data-rd-theme=\"light\""))
    }

    // MARK: - Ordered list start numbers (issue #16)

    /// troelskn's repro: a list starting at 2 must not be renumbered from 1.
    func testOrderedListHonorsStartNumber() {
        let html = MarkdownRenderer.render("2. two\n3. three").html
        XCTAssertTrue(html.contains("<ol start=\"2\">"))
        XCTAssertTrue(html.contains("<li>two</li><li>three</li>"))
    }

    func testOrderedListStartingAtZero() {
        let html = MarkdownRenderer.render("0. zero\n1. one").html
        XCTAssertTrue(html.contains("<ol start=\"0\">"))
    }

    func testOrderedListStartingAtOneHasNoStartAttribute() {
        let html = MarkdownRenderer.render("1. one\n2. two").html
        XCTAssertTrue(html.contains("<ol>"))
        XCTAssertFalse(html.contains("start="))
    }

    // MARK: - Inline emphasis across wrapped list lines (issue #15)

    /// troelskn's repro: bold spanning a lazy-continuation line in a list item.
    func testBoldAcrossWrappedListItemLines() {
        let md = """
        - Inline bold on list item **doesn't
          render**, if it line-wraps
        """
        let html = MarkdownRenderer.render(md).html
        XCTAssertTrue(html.contains("<strong>doesn&#39;t render</strong>"),
                      "emphasis must span soft-wrapped list item lines, got: \(html)")
    }

    func testItalicAcrossWrappedOrderedListItemLines() {
        let md = """
        1. first *wraps
           here* fine
        2. second
        """
        let html = MarkdownRenderer.render(md).html
        XCTAssertTrue(html.contains("<em>wraps here</em>"))
    }

    func testCodeSpanAcrossWrappedListItemStaysLiteral() {
        // A code span spanning the wrap must join before inline processing.
        let md = """
        - uses `some
          code` inline
        """
        let html = MarkdownRenderer.render(md).html
        XCTAssertTrue(html.contains("<code>some code</code>"))
    }

    // MARK: - Nested & mixed lists

    /// A nested ordered list must render inside its parent <li>, not flatten to
    /// two top-level siblings.
    func testNestedOrderedList() {
        let html = MarkdownRenderer.render("1. a\n   1. b").html
        XCTAssertEqual(html, "<ol><li>a<ol><li>b</li></ol></li></ol>")
    }

    /// A deeper ordered list keeps its own `start` number.
    func testNestedOrderedListKeepsStart() {
        let html = MarkdownRenderer.render("1. a\n   3. b\n   4. c").html
        XCTAssertEqual(html, "<ol><li>a<ol start=\"3\"><li>b</li><li>c</li></ol></li></ol>")
    }

    /// A `-` sublist inside a `1.` item nests inside the ordered <li> and does
    /// not split the parent list.
    func testUnorderedSublistInsideOrderedItem() {
        let html = MarkdownRenderer.render("1. a\n   - b\n2. c").html
        XCTAssertEqual(html, "<ol><li>a<ul><li>b</li></ul></li><li>c</li></ol>")
    }

    /// An ordered sublist inside a `-` item nests inside the unordered <li>.
    func testOrderedSublistInsideUnorderedItem() {
        let html = MarkdownRenderer.render("- a\n  1. b\n- c").html
        XCTAssertEqual(html, "<ul><li>a<ol><li>b</li></ol></li><li>c</li></ul>")
    }

    /// Three levels of alternating types nest correctly.
    func testDeeplyNestedMixedList() {
        let md = """
        1. a
           - b
             1. c
        """
        let html = MarkdownRenderer.render(md).html
        XCTAssertEqual(html, "<ol><li>a<ul><li>b<ol><li>c</li></ol></li></ul></li></ol>")
    }

    // MARK: - Loose lists

    /// A blank line between items makes the list loose: each item's text is
    /// wrapped in <p>.
    func testLooseUnorderedListWrapsItemsInParagraphs() {
        let html = MarkdownRenderer.render("- a\n\n- b").html
        XCTAssertEqual(html, "<ul><li><p>a</p></li><li><p>b</p></li></ul>")
    }

    /// A blank line between ordered items makes the ordered list loose.
    func testLooseOrderedListWrapsItemsInParagraphs() {
        let html = MarkdownRenderer.render("1. a\n\n2. b").html
        XCTAssertEqual(html, "<ol><li><p>a</p></li><li><p>b</p></li></ol>")
    }

    /// A multi-paragraph item keeps its continuation paragraph inside the <li>
    /// (it used to eject to top level and restart the list) and makes the list
    /// loose.
    func testMultiParagraphItemStaysInList() {
        let md = """
        - first

          second paragraph
        - third
        """
        let html = MarkdownRenderer.render(md).html
        XCTAssertEqual(html, "<ul><li><p>first</p><p>second paragraph</p></li><li><p>third</p></li></ul>")
    }

    // MARK: - Link & image titles

    func testLinkWithTitle() {
        XCTAssertEqual(
            MarkdownRenderer.render("[x](https://a.com \"hi\")").html,
            "<p><a href=\"https://a.com\" title=\"hi\">x</a></p>"
        )
    }

    func testImageWithTitle() {
        XCTAssertEqual(
            MarkdownRenderer.render("![a](https://a.com/i.png \"hi\")").html,
            "<p><img src=\"https://a.com/i.png\" alt=\"a\" title=\"hi\"></p>"
        )
    }

    func testLinkWithSingleQuotedTitle() {
        XCTAssertEqual(
            MarkdownRenderer.render("[x](https://a.com 'hi')").html,
            "<p><a href=\"https://a.com\" title=\"hi\">x</a></p>"
        )
    }

    /// A destination with no title behaves exactly as before (no title attribute).
    func testLinkWithoutTitleUnchanged() {
        XCTAssertEqual(
            MarkdownRenderer.render("[Click](https://example.com)").html,
            "<p><a href=\"https://example.com\">Click</a></p>"
        )
    }

    func testLinkTitleIsHTMLEscaped() {
        XCTAssertEqual(
            MarkdownRenderer.render("[x](https://a.com \"a<b&c\")").html,
            "<p><a href=\"https://a.com\" title=\"a&lt;b&amp;c\">x</a></p>"
        )
    }

    // MARK: - Reference links

    func testFullReferenceLink() {
        XCTAssertEqual(
            MarkdownRenderer.render("[text][ref]\n\n[ref]: https://a.com").html,
            "<p><a href=\"https://a.com\">text</a></p>"
        )
    }

    func testCollapsedReferenceLink() {
        XCTAssertEqual(
            MarkdownRenderer.render("[text][]\n\n[text]: https://a.com").html,
            "<p><a href=\"https://a.com\">text</a></p>"
        )
    }

    func testShortcutReferenceLink() {
        XCTAssertEqual(
            MarkdownRenderer.render("[ref]\n\n[ref]: https://a.com").html,
            "<p><a href=\"https://a.com\">ref</a></p>"
        )
    }

    func testReferenceLinkLabelIsCaseInsensitive() {
        XCTAssertEqual(
            MarkdownRenderer.render("[Text][REF]\n\n[ref]: https://a.com").html,
            "<p><a href=\"https://a.com\">Text</a></p>"
        )
    }

    func testReferenceLinkWithTitle() {
        XCTAssertEqual(
            MarkdownRenderer.render("[text][ref]\n\n[ref]: https://a.com \"hi\"").html,
            "<p><a href=\"https://a.com\" title=\"hi\">text</a></p>"
        )
    }

    /// An undefined reference renders as its literal source text.
    func testUndefinedReferenceRendersLiteral() {
        XCTAssertEqual(
            MarkdownRenderer.render("[text][nope]\n\n[real]: https://a.com").html,
            "<p>[text][nope]</p>"
        )
    }

    /// A definition line produces no output of its own.
    func testReferenceDefinitionLineDoesNotRender() {
        XCTAssertEqual(MarkdownRenderer.render("[ref]: https://a.com").html, "")
    }

    /// Definitions are threaded through the list parser, so a reference link
    /// inside a list item resolves.
    func testReferenceLinkInsideListItem() {
        XCTAssertEqual(
            MarkdownRenderer.render("- see [text][ref]\n\n[ref]: https://a.com").html,
            "<ul><li>see <a href=\"https://a.com\">text</a></li></ul>"
        )
    }

    // MARK: - Reference images

    func testFullReferenceImage() {
        XCTAssertEqual(
            MarkdownRenderer.render("![alt][img]\n\n[img]: https://a.com/i.png").html,
            "<p><img src=\"https://a.com/i.png\" alt=\"alt\"></p>"
        )
    }

    func testCollapsedReferenceImage() {
        XCTAssertEqual(
            MarkdownRenderer.render("![alt][]\n\n[alt]: https://a.com/i.png").html,
            "<p><img src=\"https://a.com/i.png\" alt=\"alt\"></p>"
        )
    }

    func testShortcutReferenceImage() {
        XCTAssertEqual(
            MarkdownRenderer.render("![alt]\n\n[alt]: https://a.com/i.png").html,
            "<p><img src=\"https://a.com/i.png\" alt=\"alt\"></p>"
        )
    }

    func testReferenceImageWithTitle() {
        XCTAssertEqual(
            MarkdownRenderer.render("![alt][img]\n\n[img]: https://a.com/i.png \"cap\"").html,
            "<p><img src=\"https://a.com/i.png\" alt=\"alt\" title=\"cap\"></p>"
        )
    }

    /// An undefined reference image renders as its literal source text.
    func testUndefinedReferenceImageRendersLiteral() {
        XCTAssertEqual(
            MarkdownRenderer.render("![alt][nope]\n\n[real]: https://a.com/i.png").html,
            "<p>![alt][nope]</p>"
        )
    }

    /// A reference image resolving to an unsafe URL is dropped to literal text.
    func testReferenceImageUnsafeURLDropped() {
        let html = MarkdownRenderer.render("![x][bad]\n\n[bad]: javascript:alert(1)").html
        XCTAssertFalse(html.contains("<img"))
        XCTAssertFalse(html.contains("javascript"))
    }

    /// Reference images resolve inside a list item too (refs are threaded through).
    func testReferenceImageInsideListItem() {
        XCTAssertEqual(
            MarkdownRenderer.render("- ![alt][img]\n\n[img]: https://a.com/i.png").html,
            "<ul><li><img src=\"https://a.com/i.png\" alt=\"alt\"></li></ul>"
        )
    }

    // MARK: - Thematic break after a list

    /// A thematic break directly under a list item (no blank line) closes the
    /// list and renders as `<hr>`, rather than being swallowed as lazy text.
    func testThematicBreakClosesListWithoutBlankLine() {
        XCTAssertEqual(
            MarkdownRenderer.render("- a\n***").html,
            "<ul><li>a</li></ul>\n<hr>"
        )
    }

    // MARK: - GFM bare-URL autolinking

    func testBareURLAutolinked() {
        XCTAssertEqual(
            MarkdownRenderer.render("Visit https://x.com now").html,
            "<p>Visit <a href=\"https://x.com\">https://x.com</a> now</p>"
        )
    }

    /// A bare URL inside a code span stays literal (code is stashed first).
    func testBareURLInCodeSpanNotAutolinked() {
        XCTAssertEqual(
            MarkdownRenderer.render("`https://x.com`").html,
            "<p><code>https://x.com</code></p>"
        )
    }

    /// Trailing sentence punctuation is left outside the link.
    func testBareURLTrailingPunctuationTrimmed() {
        XCTAssertEqual(
            MarkdownRenderer.render("(see https://x.com).").html,
            "<p>(see <a href=\"https://x.com\">https://x.com</a>).</p>"
        )
    }
}
